### ISSUE TITLE
Not working with any functions

### ISSUE THREAD

**Issue by ashvar** [davedelong/DDMathParser#105]
It always returns nil for every function request I make, even in sample console app.
Try yourself `sin(2)`, `cos(pi)`.. It even fails with difficult scopes arrangement.. What am I doing wrong? Or is it an issue with entire framework?

Have tried in xCode 6, xCode 7, Mac OSX app, Mac OSX Console app, iPhone app.
I try it by simply calling `-numberByEvaluatingString` for NSString and directly through DDMathEvaluator.

**Comment by davedelong** [comment]
On the latest El Capitan beta with the latest Xcode beta, using the latest code in the repository, it works fine for me:

    > sin(2)
    	Parsed: sin(2)
    	Rewritten as: 0.9092974268256817
    	Evaluated: 0.9092974268256817
    	numberByEvaluatingString: 0.9092974268256817
    > sin(2°)
    	Parsed: sin(dtor(2))
    	Rewritten as: 0.03489949670250097
    	Evaluated: 0.03489949670250097
    	numberByEvaluatingString: 0.03489949670250097
    > cos(pi)
    	Parsed: cos(pi())
    	Rewritten as: -1
    	Evaluated: -1
    	numberByEvaluatingString: -1
    >

**Comment by ashvar** [comment]
Thanks for checking it out.
Found the issue. It appears if you are calling the following methods for default evaluator:

> [DDMathOperator addTokens:@[@"or"] forOperatorFunction:DDOperatorLogicalOr];
> [DDMathOperator addTokens:@[@"and"] forOperatorFunction:DDOperatorLogicalAnd];
> [DDMathOperator addTokens:@[@"not"] forOperatorFunction:DDOperatorLogicalNot];

P.S.: Taken from here: https://github.com/davedelong/DDMathParser/wiki/Operators

**Comment by davedelong** [comment]
Ah, yep! The tokenizer is seeing the `n` in `sin(2)` and thinking it might be the start of the `not` operator, and so it's prematurely ending tokenization of the `sin` token.

**Comment by davedelong** [comment]
You'd see the same issue with `cos(pi)`, because it would think the `o` is the start of the `or` operator.

**Comment by davedelong** [comment]
I should point out, however, that this is working on the 1.1 branch.

**Comment by davedelong** [comment]
... and this works on the 2.0 branch, which will be merged in to master soon.
