### ISSUE TITLE
Case-sensitive functions

### ISSUE THREAD

**Issue by davedelong** [davedelong/DDMathParser#110]
By default, functions are case-insensitive, but there have been two requests for them, so it seems worthwhile to investigate allowing this.

**Comment by liaujianjie** [comment]
Thanks for looking into this. I think case-sensitive functions are much better because they are much more mathematically correct/accurate. E.g. `F(x)` is known as the integral of `f(x)` in calculus.

**Comment by davedelong** [comment]
By default, `Evaluator` uses case-insensitive functions.

However, you can now change this when you create your `Evaluator` by doing:

    let eval = Evaluator(usesCaseSensitiveFunctions: false)

Then the `Evaluator` will evaluate functions as case *sensitive*.
