### ISSUE TITLE
Consecutive factorial token does not evaluate correctly

### ISSUE THREAD

**Issue by liaujianjie** [davedelong/DDMathParser#114]
For example, `3!!` gives a value of `3` instead of the expected value of `720`. `(3!)!` returns the correct value, however.

**Unit test snippet:**

    func testJJIssue1() {
        guard let d = XCTAssertNoThrows(try "3!!".evaluate()) else { return }
        XCTAssertEqual(d, 720)
    }

**Console log:**

    error: -[MathParserTests.GithubIssues testJJIssue1] : XCTAssertEqual failed: ("Optional(3.0)") is not equal to ("Optional(720.0)") -

**Comment by davedelong** [comment]
This is correct behavior. `!!` is the [double factorial](https://en.wikipedia.org/wiki/Double_factorial) operator.

**Comment by liaujianjie** [comment]
My bad, I had no idea this was a thing. It was quite confusing for my test users because it isn't commonly used. Thanks for the clarification.
