### ISSUE TITLE
CodeSign error: code signing is required for product type 'Framework' in SDK 'iOS 9.1'

### ISSUE THREAD

**Issue by nikolaenkoag** [davedelong/DDMathParser#116]
Hi! I am add DDMathParser.xcodeproj to my workspace and link MathParser.framework into my app.

When i build my project in ios 9.1 device, i get:
CodeSign error: code signing is required for product type 'Framework' in SDK 'iOS 9.1'

How do I solve the problem?

**Comment by davedelong** [comment]
You may need to edit the build settings for the framework when building your app so that the framework gets code signed using whatever identity you're using for the rest of your app.
