### ISSUE TITLE
enum Operator confusing with MathParser.Operator

### ISSUE THREAD

**Issue by steve-h** [davedelong/DDMathParser#122]
I was having trouble getting swift to find the MathParser module namespace when I was using MathParser inside an internal framework. I had to copy code and redefine the Operator enum values.

swift 3 seems to be promoting lowercase enum values so when the swift 3 big rename, can you use lowercase "operator".

documenting how to do the modulemap for the use inside other frameworks may also help.

```
public struct ResolvedToken {
    public enum Kind {
        case Number(Double)
        case Variable(String)
        case Identifier(String)
        case Operator(MathParser.Operator)
    }
    
    public let kind: Kind
    public let string: String
    public let range: Range<String.Index>
}
```
My override was:
```
public struct ResolvedToken {
    public enum Kind {
        case Number(Double)
        case Variable(String)
        case Identifier(String)
//        case Operator(MathParser.Operator)
        case RTOperator(Operator)
    }
```
Awesome library!

**Comment by davedelong** [comment]
Hey @steve-h, thanks for reporting this.

I hit this on the `swift3` branch, and solved it by backtickking the enum case: https://github.com/davedelong/DDMathParser/blob/swift3/MathParser/ResolvedToken.swift#L16
