### ISSUE TITLE
Xcode 8b6 doesn’t like extensions using private vars

### ISSUE THREAD

**Issue by joshdistler** [davedelong/DDMathParser#127]
Breaks in a number of places because of this.

**Comment by joshdistler** [comment]
Apparently fileprivate will do what private was doing previously.

**Comment by joshdistler** [comment]
Hi Dave. Know when you’ll be updating this? Waiting on GM?

**Comment by davedelong** [comment]
I'm waiting on having time to download the latest seed 😉

I'll try and make that a priority to do today.

**Comment by davedelong** [comment]
Fixed.
