### ISSUE TITLE
Swift 3 Conversion Errors

### ISSUE THREAD

**Issue by MarkOfSydney** [davedelong/DDMathParser#129]
Conversion to Swift 3 generated the following error. Please advise if there is a workaround or release date of a Swift 3 version. Thanks heaps; the DDMathParser is simply brilliant.

/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/objdump: '/Users/mazenkilani/Library/Developer/Xcode/DerivedData/8Calc-fstijmwatjfdevfmpimywmndifyk/Build/Intermediates/SwiftMigration/8Calc/Products/Debug-iphonesimulator/8Calc.app/Frameworks/MathParser.framework/MathParser': No such file or directory.
fatal error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/otool: internal objdump command failed

**Comment by davedelong** [comment]
I just pushed version 3.0, which is fully Swift 3 compatible. It's on the `master` branch, or is the `3.0.0` tag.

**Comment by Sweeper777** [comment]
What do I write in the podfile if I want to install the swift 3 version?

**Comment by dsmailes** [comment]
pod ‘DDMathParser’, :git => 'https://github.com/davedelong/DDMathParser.git’, :tag => ‘3.0.0’

**Comment by Sweeper777** [comment]
Thank you!
