### ISSUE TITLE
Where have usage samples (real-world) disappeared?

### ISSUE THREAD

**Issue by Motti-Shneor** [davedelong/DDMathParser#131]
I integrated older version (v1.1) of DDMathParser into my Mac App. It was wonderful. Easy to build and use. I cloned, dropped in a few sources, added DDMathParser git repo as a git submodule to my repo, and built it directly into my App.

At that time, there were bunch of great little sample project targets to show you things like - how to bind text fields against an evaluator, how to get errors and display them, how to continuously re-parse math text and display the outcome etc.  and of course - it all was Obj-C.

Now not only DDMathParser became Swift (which regrettably I don't master yet) and a standalone framework, but all the "how to integrate into your app" samples completely disappeared. Of course I can decipher the unit-tests for sample usage (math-wise) and learn independently how to integrate swift framework into my older Obj-C App project - but this is both time consuming and prone to unoptimized integration (my use of DDMathParser is quite heavy - millions of calculations in near real time).

I DO want to replace my old DDMathParser (especially after reading all those issues that have been solved since then) but I am not fluent with Obj-C to Swift integration, and the DDMathPArser also changed several aspects of its behavior

Can the author (or other, more experienced users) add some sample code to the repo, of usage in real-world applications, for the benefit of such as myself?

**Comment by davedelong** [comment]
There's a new Demo app on the `swift4` branch that shows how to tap in to each stage of parsing and evaluation. Please check that out and let me know if you have questions. :)
