### ISSUE TITLE
a bug

### ISSUE THREAD

**Issue by peterhoucll** [davedelong/DDMathParser#132]
do {
            let expression = try Expression(string: "10.2 - 10.1")
            let result = try Evaluator.default.evaluate(expression)
            print("result = \(result)")
        } catch {}
       //result = 0.0999999999999996

        do {
            let result = try "10.2 - 10.1".evaluate()
            print("result = \(result)")
        } catch { }
       //result = 0.0999999999999996

**Comment by davedelong** [comment]
Yep. This is the same as issue #99 and there's not a lot I can do about it. 😞
