### ISSUE TITLE
Swift 3:  Deprecated constants M_PI, DBL_MAX, DBL_MIN trigger warnings on build

### ISSUE THREAD

**Issue by edovey** [davedelong/DDMathParser#137]
Examples:  

.../Pods/DDMathParser/MathParser/Functions+Defaults.swift:188:63: 'DBL_MIN' is deprecated: Please use 'Double.leastNormalMagnitude' or '.leastNormalMagnitude'.

.../Pods/DDMathParser/MathParser/Functions+Defaults.swift:696:23: 'M_PI' is deprecated: Please use 'Double.pi' or '.pi' to get the value of correct type and avoid casting.

Build target is iOS 9.1, using Swift (3), Xcode 8.3.2.

**Comment by nezhyborets** [comment]
Same issue here. @edovey what version of DDMathParser do you have? My cocoapods downloads 2.0.0 for some reason, but it seems that the most recent version is 3.0.0

**Comment by edovey** [comment]
Version 3.0.0 (Swift).  My podfile has this entry for DDMathParser:

    pod 'DDMathParser', :git => 'https://github.com/davedelong/DDMathParser.git', :tag => '3.0.0'

**Comment by edovey** [comment]
Issue disappears with Xcode 8.3.3.

**Comment by davedelong** [comment]
This should be fixed on the `master` and `swift4` branches.

**Comment by edovey** [comment]
Thank you!

**Comment by nezhyborets** [comment]
Works on master but Cococapods still gives 2.0.0, so switched to Submodules
