### ISSUE TITLE
Incorrect evaluation of mixed fractions

### ISSUE THREAD

**Issue by Roman-Kerimov** [davedelong/DDMathParser#142]
For example, "2½".evaluate() returns 1 instead of 2.5

**Comment by davedelong** [comment]
Ah... yes, because it's parsing the `2`, and then the `½`... it sees them as separate tokens, and assumes they're an implicit multiplication.

**Comment by davedelong** [comment]
But I agree that's not ideal. :)

**Comment by davedelong** [comment]
ok, I've got a rudimentary fix in place, but this has actually highlighted a deeper problem with DDMathParser's token resolution. 

The current fix is to inject a `+` operator in between a number and a fraction, however that will break evaluation for things like `2½ * 2`, because:

**Comment by Roman-Kerimov** [comment]
I think that this problem can be solved by adding a special addition operator with the highest priority.

**Comment by davedelong** [comment]
@Roman-Kerimov you're right, that's probably a simpler fix than what I was thinking. The fix has been pushed to `master`. Thanks!
