### ISSUE TITLE
-2++3 gives -5

### ISSUE THREAD

**Issue by horaceho** [davedelong/DDMathParser#145]
`-2+3` gives `-1`
`-2++3` gives `-5`

Is this a bug?

**Comment by davedelong** [comment]
sure looks like it

**Comment by davedelong** [comment]
Yep, this one is really subtle in what's going on. I think I've narrowed it down though.

**Comment by davedelong** [comment]
Fixed on the `swift-4` branch

**Comment by davedelong** [comment]
This one was devious. Thank you for finding and reporting it!
