### ISSUE TITLE
nil/null support in if statements

### ISSUE THREAD

**Issue by HarshSharma12** [davedelong/DDMathParser#149]
We are trying to parse the following function :- attr1 - if(attr2==nil, 0,attr2)

Is the syntax correct because the value returned is long max.

Using latest version of DDMathParser (Swift 4.0).

**Comment by davedelong** [comment]
Yeah, `nil` isn’t really a thing in DDMathParser, because numeric values always exist. In the case of variables, an error will be thrown during evaluation if the variable value is missing. Therefore, checking for `nil` isn’t necessary.
