### ISSUE TITLE
Handling % like a "traditional" calculator

### ISSUE THREAD

**Issue by blackjack75** [davedelong/DDMathParser#20]
I have this issue in my (DDMathParser powered) iOS calculator app that several users complain about the % being treated a modulo. Since they're not all math-heads, they  want a "traditional" calculator with a percent key.

Basically what they want it to add or remove percentages to the previous referred value like this:
250 + 10% 

Obviously they want is this output :
250 + (0.10*250) 

a) I was wondering if you had an idea of an approach I could take to implement this? 
b) if you do, would you accept money to implement it yourself in DDMathParser (that would be an optional calculation mode ) ?

**Comment by chetem** [comment]
I know this is an old issue, but is this functionality still supported?

**Comment by davedelong** [comment]
@chetem yes. At the very least, you can configure this when creating an `OperatorSet`. I think there are other places you can set this too, but it all funnels through there.

**Comment by chetem** [comment]
Strange, it didn't seem to be working for me. I tried a simple example (actually the same one you used) and did `try "250 + 10%".evaluate()` but ended up in the catch block. I'll play around some more though, thanks for getting back to me.

**Comment by davedelong** [comment]
@chetem You'd do it like this:

    let operatorSet = OperatorSet(interpretsPercentSignAsModulo: false)
    let e = try Expression(string: "250 + 10%", operatorSet: operatorSet)
    let v = try Evaluator.default.evaluate(e) // v == 275

**Comment by chetem** [comment]
Great, thanks @davedelong. I'll give that a try 👍

**Comment by tirrorex** [comment]
Exactly what i was looking for ! Thanks :)
