### ISSUE TITLE
I want 7+5%=7.05.How to do?

### ISSUE THREAD

**Issue by zl19850227** [davedelong/DDMathParser#41]

**Comment by hadwanihardik** [comment]
By using following method i have resolved this issue.

+(NSString *)fotmatStringForPercentFunction:(NSString *)string
{

    NSUInteger count = 0, length = [string length];
    NSRange range = NSMakeRange(0, length);
    while(range.location != NSNotFound)
    {
        range = [string rangeOfString: @"%" options:0 range:range];
        if(range.location != NSNotFound)
        {
            
            for (NSInteger charIdx=range.location-1; charIdx>=0; charIdx--)
            {
                char ch=[string characterAtIndex:charIdx];
               // NSLog(@"%c", ch);
                NSCharacterSet *numericSet = [NSCharacterSet decimalDigitCharacterSet];
                if ((![numericSet characterIsMember:ch] || ch == ')') && ch != '.')
                {
                   // NSLog(@"operand for percentage %@ ",[string substringWithRange:NSMakeRange(charIdx+1,range.location-charIdx)]);
                    string=[string stringByReplacingOccurrencesOfString:[string substringWithRange:NSMakeRange(charIdx+1,range.location-charIdx)] withString:[NSString stringWithFormat:@"percent(%@) ",[string substringWithRange:NSMakeRange(charIdx+1,range.location-charIdx-1)]]];
                   // NSLog(@"Replaced - %@",string);
                    break;
                }
                if (charIdx == 0 && [numericSet characterIsMember:ch])
                {
                    //NSLog(@"operand for percentage %@ ",[string substringWithRange:NSMakeRange(charIdx,range.location-charIdx)]);
                    string=[string stringByReplacingOccurrencesOfString:[string substringWithRange:NSMakeRange(charIdx,range.location-charIdx+1)] withString:[NSString stringWithFormat:@"percent(%@) ",[string substringWithRange:NSMakeRange(charIdx,range.location-charIdx)]]];
                   // NSLog(@"Replaced - %@",string);
                    break;
                }
               
            }
            range = NSMakeRange(range.location + range.length, length - (range.location + range.length));

            count++; 
        }
    }
    if ([string containsString:@"%"])
    {
        return [self fotmatStringForPercentFunction:string];
    }
    return string;
}
