### ISSUE TITLE
Using a string as an argument in a custom function.

### ISSUE THREAD

**Issue by ChrisBeeson** [davedelong/DDMathParser#42]
Hi,

I would like to make a function which would allow me to pass a string in the argument - what's the best way to do this?  

eg..
Moles("Ca(OH)2")

Any help would be extremely gratefully received.

**Comment by patricks** [comment]
I also would love such a feature. 😉

**Comment by davedelong** [comment]
@patricks fortunately, it's in! Quoted strings show up as Variable tokens, and it's up to you to supply a numeric value for it at evaluation time.

**Comment by patricks** [comment]
@davedelong that sounds amazing, but my test code fails:

```swift
let a1function = Function(name: "a1") { (state) -> Double in
    let arg1 = try state.evaluator.evaluate(state.arguments[0], substitutions: state.substitutions)
    return 0
}

let evaluator = Evaluator()

try! evaluator.registerFunction(a1function)
let expression = try! Expression(string: "a1('hello')")
let result = try! evaluator.evaluate(expression)
```

Can you tell me what I did wrong? I get the following error message:

`Fatal error: 'try!' expression unexpectedly raised an error: MathParser.MathParserError(kind: MathParser.MathParserError.Kind.unknownVariable("hello"), range: Range(3..<10))`

**Comment by davedelong** [comment]
@patricks your `let arg1 = ...` line is attempting to evaluate the value of the `$hello` variable, but the substitution dictionary is empty, and so it's throwing an error saying "I don't know the value of `$hello`".

If you provide a `substitutions:` parameter to the `.evaluate(...)` call, or you provide a dynamic variable resolver, then it'll work just fine.

**Comment by patricks** [comment]
`VariableResolver` didn't also know nothing about this dynamic resolvers 👍. But I think this can't resolve my use case.

I would like to have custom functions which can import Strings and convert them into numbers. As Example

`"1 + a1('B') + roman('XXX')"` 

In this example function `a1` should use the of index the character `B` in the alphabet and function `roman` should convert the roman numeral `XXX`.

I hope this is understandable 😄. Or would you suggest that I should precalculate this functions into normal variables first, and use this one with DDMathParser?

**Comment by davedelong** [comment]
In the `a1` vs `roman` situation you describe, that'd be ideal for a custom function. You'd want the implementations to assert that the `state.arguments` array has one element that's a variable expression, and then you'd pull out the `expression.kind.variable` value to get the raw `String?` representation. From there you'd implement whatever evaluation logic you want.

**Comment by patricks** [comment]
I think the mystery is solved! 😀 Thanks so much for you help!
