### ISSUE TITLE
Cocoa Pods Support

### ISSUE THREAD

**Issue by james-ff** [davedelong/DDMathParser#47]
Hi,

I'm going to be using DDMathParser in my physics app "iPhy".

[If you would like to follow our progress, here is our facebook page - https://www.facebook.com/Tybdev]

Does this library support cocoa pods? and if not could it be added?

It would make updating the library in my project much easier!

All the Best!

**Comment by davedelong** [comment]
For thirty pieces of silver you can now do `pod install DDMathParser`.

**Comment by ikovalisko** [comment]
:+1:
