### ISSUE TITLE
Case-sensitive functions

### ISSUE THREAD

**Issue by thebear9** [davedelong/DDMathParser#57]
Is there anyway to parse functions such that the variables returned could be both/either upper and lower case?  For example, it is common practice to use 'T' for temperature but  't' is time.  Here is an example, where "returnedData" only contains 't':

    //The equation is -0.1*T/t and I'd like it to show that 'T' and 't' are unique variables
    NSString *EquationtoCheck= [NSString stringwithformat:@"-0.1*T/t"];
    NSDictionary *variables = [NSDictionary dictionaryWithObjectsandKeys:EquationtoCheck, @"input", nil];
    NSDictionary *returnedData = [NSDictionary dictionaryWithDictionary:[[MathParser alloc] ParseInfo:variables]];

**Comment by davedelong** [comment]
This will be possible using `2.0` branch. There I've added a "function overrider" that allows you to evaluate a function *before* the built-in implementations are called. The function name you're given is the non-standardized name of the function, so you could (in your implementation of the override) perform case-sensitive evaluations.

The `2.0` branch will be merged into the `master` branch soon.

**Comment by davedelong** [comment]
I added a unit test for this, which demonstrates how to implement the `FunctionOverrider`.

**Comment by thebear9** [comment]
This sounds great!  I'm looking forward to incorporating it in my apps.  

I gave a webinar on mobile app development yesterday and mentioned DDMathParser and CHCSVParser (right about the 50:00 minute mark):

https://www.youtube.com/watch?v=tSlFMui-_wc

Jason
