### ISSUE TITLE
Question about performance, and integration with CoreData

### ISSUE THREAD

**Issue by Motti-Shneor** [davedelong/DDMathParser#58]
Hello, and big hand for beautiful DDMathParser. I intend to use it in an application I write. I will be using mass calculations on a CoreData database - you can think of it as a series of columns in a spreadsheet with the first columns containing values, then columns containing math expressions based on these values (hence the need for variables in expressions) and last several more layers of statistical and other calculations based on the results of those "columns" containing math expressions. 

The normal stuff will be about 2000-3000 rows each time, and I expect math expressions containing mostly basic arithmetics and parentheses --- occasionally a function (I'm calculating the volume and biomass of micro-organisms), then do statistics and aggregation on them.

Now --- I don't know how fast is DDMathParser, and is there a faster parser I should check before I integrate it into my project. 

Have you done any benchmarking on it? Is there at all a way to benchmark math parsers?

Thanks!

**Comment by davedelong** [comment]
To be honest, performance has never been a major goal of `DDMathParser`: it's goals have been correctness and extensibility. 

So, no I have done no benchmarking on it, other than to notice that the unit tests currently perform about 5000 expression evaluations over about 4 seconds. This is hardly scientific, however. ;)
