### ISSUE TITLE
Add NSLocale support

### ISSUE THREAD

**Issue by JanX2** [davedelong/DDMathParser#60]
For this, `-_parseNumberWithError:` will have to be extended to honor the `NSLocaleDecimalSeparator`, be made aware of a potential thousands separator it needs to pass over (available via `NSLocaleGroupingSeparator`).

Also DD_IS_DIGIT() needs to know about digits in other writing systems.

Finally, `_DDNumberTerm` can’t simply use `[[self token] numberValue]` anymore. This needs to be rewritten using `NSNumberFormatter`. 

For performance reasons, we would have to have some shared `NSNumberFormatter` available for this. One solution would be to have one available in the `DDParser` and setting a new property or ivar of the `_DDNumberTerm` within `-resolveWithParser:error:` to that formatter for use in `-expressionWithError:`. We could call this property `numberFormatter` ;-).

**Comment by davedelong** [comment]
This is implemented on the `2.0`, which will be merged into `master` soon. Note, however, that when parsing according to a locale, numbers in scientific notation are *not* supported.

**Comment by JanX2** [comment]
@davedelong :thumbsup:
