### ISSUE TITLE
No negative nthroot's

### ISSUE THREAD

**Issue by AppleDeveloper98** [davedelong/DDMathParser#63]
Hi,
I Use DDMathParser in my App but currently there is a issue and the result is not correct.
When I write:
```objective-c
NSNumber *number = [@"nthroot(-27,3)" numberByEvaluatingString];
NSLog(@"%@", number);
```
Is number "nan". Why? The third root from "-27" is possible and is "-3". What can I do that it works?

Best regards
Nils

**Comment by davedelong** [comment]
This is fixed on the `2.0` branch, which will be merged in to `master` in the coming weeks.
