### ISSUE TITLE
atan incorrect evaluation

### ISSUE THREAD

**Issue by StevenTso** [davedelong/DDMathParser#76]
Using the settings:
```
    DDMathEvaluator *evaluator = [[DDMathEvaluator alloc] init];
    evaluator.usesHighPrecisionEvaluation = YES;
    evaluator.AngleMeasurementMode = DDAngleMeasurementModeDegrees;
```
Evaluation of atan(1) results in 45.19097... and not 45.

Reproducible using the demo provided in DDMathParser and adding the lines highlighted.
![screen shot 2014-06-16 at 8 18 59 pm](https://cloud.githubusercontent.com/assets/2614673/3295007/0cd26756-f5b5-11e3-8b93-184207db3707.png)

**Comment by davedelong** [comment]
Closing, since the high-precision mode is no longer available in DDMathParser.
