### ISSUE TITLE
Rewriting expression not working

### ISSUE THREAD

**Issue by liaujianjie** [davedelong/DDMathParser#79]
I tried to rewrite some expressions and all of them couldn't work. I then tested some of the rewrites provided in *DDExpressionRewriter.m*, for example:

I tested

    [self addRewriteRule:@"abs(__exp1)" forExpressionsMatchingTemplate:@"sqrt(__exp1 ** 2)" condition:nil];

by evaluating `(99**80)**2` and `sqrt((99**80)**2)`, I get `+∞`. (I can get a value for `99**80`)

Meaning the rewrite rule above is not even utilised. Or am I doing something wrong here?

**Comment by davedelong** [comment]
This should be fixed on the `2.0` branch, which will be merged into `master` soon.

**Comment by liaujianjie** [comment]
Thanks for your work!
