### ISSUE TITLE
Wiki improvements

### ISSUE THREAD

**Issue by JanX2** [davedelong/DDMathParser#88]
I just pushed my commit “Small improvements and fixes for typos.” to 

https://github.com/JanX2/DDMathParser.wiki.git

You can clone 

https://github.com/davedelong/DDMathParser.wiki.git

locally, add my URL above as a remote, fetch that, point your master branch to the commit locally and push that branch to your wiki. I couldn’t find a more convenient way.

**Comment by davedelong** [comment]
Thanks. Now that the Swift implementation is largely finished, I'm working on updating the wiki to match the new code.
