### ISSUE TITLE
Functions with Multiple Arrays as Arguments

### ISSUE THREAD

**Issue by thebear9** [davedelong/DDMathParser#89]
It seems that DDMathParser could handle custom functions that need two (or more) arrays as arguments.

For example, a linear regression:

slope([array of x values], [array of y values])

Is this possible in the current release?  If so, what is the character/string that would be used to interpret where the first array ends and second array begins?

**Comment by davedelong** [comment]
This is not possible. There is no notion of a collection of values being a single argument.

**Comment by davedelong** [comment]
Thinking about this some more, I'm not seeing a way to easily incorporate this into the parser.

However, you could write a `slope` function that just takes a list of numbers, and either assumes they come in the form of `slope(x₁, y₁, x₂, y₂, x₃, y₃, ..., xₓ, yₓ)` or `slope(x₁, x₂, x₃, ..., xₓ, y₁, y₂, y₃, ..., yₓ)`.

Based on this, I'm not going to implement array arguments unless I have a pretty significant epiphany on how this would be possible.
