### ISSUE TITLE
What is the recommended point in the repository I should use in my App?

### ISSUE THREAD

**Issue by Motti-Shneor** [davedelong/DDMathParser#90]
Hi. I've been using DDMathParser in my project with great success. The Application (for Water biosphere analysis via microscope imaging) was developed for a specific scientific lab and currently cannot be purchased  on the internet.  I believe it will soon be available for free to scientists.  then I'll add it to the list of Apps using DDMathParser.

However --- I added it as a submodule to my git repository, and since then it didn't update. It seems "Master" is stuck back in the past, and I haven't seen any recommendation to use another branch.

I'm using SDK 10.9, and deploy on 10.8 and on. My app is pretty modern, all ARC and CoreData etc. 

What branch should I use? Is 1.1 stable? Are there Interface changes?

**Comment by davedelong** [comment]
The `1.1` branch has the most features, but all development is currently happening on the `2.0` branch, which will supersede both `master` and `1.1` in the coming weeks.
