### ISSUE TITLE
variable name starting with '_'

### ISSUE THREAD

**Issue by farfromrefug** [davedelong/DDMathParser#92]
Would be nice to support variable names starting with '_'.

I successfully by simply modifying that [line](https://github.com/davedelong/DDMathParser/blob/master/DDMathParser/DDMathStringTokenizer.m#L320) with this:
```
    if (token == nil && (next == '$' ||  next == '_')) {
```

**Comment by davedelong** [comment]
This is fixed on the `2.0` branch, which will be merged in to `master` soon.

**Comment by farfromrefug** [comment]
Great ! Didn't know about 2.0!
Will there be big changes, improvements?

**Comment by davedelong** [comment]
Functionally it should be fairly equivalent to 1.x, although I'm not sure I'll be porting the high-precision evaluator yet. The big change is that the whole thing has been rewritten in Swift 2.0.

**Comment by farfromrefug** [comment]
Ok nice! Even if i am not yet ready for swift ;)

Thanks !
