### ISSUE TITLE
What branch shall I use? What is the current state of the project?

### ISSUE THREAD

**Issue by Motti-Shneor** [davedelong/DDMathParser#93]
Hello Dave and everyone. I made DDMathParser (master) a submodule of one of my projects, and enjoy using it a lot.

However, I saw many important issues and bugs resolved onto branch 1.1, and I suspect for lack of time or resources the changes and fixes never reached master.

Can someone "recommend" the latest stable version of DDMatphParser?

**Comment by davedelong** [comment]
Duplicate of #90
