### ISSUE TITLE
wrong expression result

### ISSUE THREAD

**Issue by mayank4ios** [davedelong/DDMathParser#96]
It gives wrong expression results for trigonometry operations. for example the value of  tan(45) is 1 but it gives 1.6 something. please check.

Thanks.

**Comment by davedelong** [comment]
By default, trigonometric functions are interpreting their parameters to be in radians, not degrees.

If you want the parameter to be interpreted as degrees, there are a couple of ways you can do this:

1. Add the degree sign to the parameter: `tan(45°)`
1. Wrap the parameter in the `dtor` function (which is what the ° operator does, essentially): `tan(dtor(45))`
1. Alter the `angleMeasurementMode` of your `DDMathEvaluator`. This will change the interpretation of parameters for all future evaluations using that evaluator object.

        [DDMathEvaluator sharedMathEvaluator].angleMeasurementMode = DDAngleMeasurementModeDegrees;
        NSLog(@"%@", [@"tan(45)" numberByEvaluatingString]);

**Comment by mayank4ios** [comment]
ok thanks... :)

**Comment by mayank4ios** [comment]
hello,
Is it possible to get correct result without brackets.. 

for example: I want to find the value of  tan(45°) , can I get result by calling tan45° ?

**Comment by davedelong** [comment]
No, not without significant alterations to the fundamental workings of the math parser.
