### ISSUE TITLE
Logic expressions. Compare Strings

### ISSUE THREAD

**Issue by YaroslavVoloshyn** [davedelong/DDMathParser#97]
Hi @davedelong! Thank you for the useful library. I would like to use it in my project. But for me need feature for compare Strings. For example: " ('B' != 'A') && ('k' != 'K') ". Is the easy way to add this functionality to your library?

**Comment by davedelong** [comment]
Theoretically this is possible, but it's not currently very easy to do. I'll investigate making this simpler.

**Comment by davedelong** [comment]
I've added a very rudimentary way of doing this on the `2.0` branch. You'll supply a `FunctionOverrider` to the `Evaluator`. It will get invoked every time the evaluator attempts to evaluate a function, and you get the chance to do your own fancy processing.

- return a `Double` to inject your own result for the function
- return `nil` to indicate you don't have anything special to do (at which point the built-in implementation will be used)
- throw an error to indicate something went wrong (and evaluation will abort)

The `2.0` branch will be merged in to `master` soon.
