### ISSUE TITLE
Differentiating _e_ (Euler's constant) and scientific notation e?

### ISSUE THREAD

**Issue by blackjack75** [davedelong/DDMathParser#98]
Is this the expected behaviour?

When I enter "5e" the e is interpreted as Euler's constant (2.71xxx).
When I enter "5e0" its it evaluated as 5. 

I would expect 5e to be interpreted as 5e0 (or an error).

We already have e() to get Euler's constant. Why does a lonely 'e' get interpreted as (e)?
 

![screen shot 2015-03-18 at 20 17 43](https://cloud.githubusercontent.com/assets/473158/6721566/308da856-cdad-11e4-9798-77e627be359e.png)

**Comment by davedelong** [comment]
The `5e0` is scientific notation for `5 x 10⁰`. However, scientific notation only works if there's an exponent number (the `0`). If it's not there, then the parser will only parse the number as `5`, since `5e` is not a number. Once `5` has been parsed as a number, it parses the next token as `e`. `e` is interpreted as a function expression, under the rules of argument-less functions. And since there's a function defined as `e()` (to return 2.718....), `5e` gets parsed as `5 * e()`.

**Comment by blackjack75** [comment]
Thanks! That was quick :-)

As you know I have an iOS app that looks like a regular calculator (but supports long formulas) so it feels a bit weird *while* people type '5e' and get ready to type the exponent and it appears as (2*2.71...).

Where'd you'd think it would be the best place to overload this behaviour without messing stuff up too much.? I am thinking about disabling argument-less functions altogether but maybe there's a simple way. I wish I could just rename e() to euler() or something like that.

**Comment by blackjack75** [comment]
I am thinking about calling     [[DDMathEvaluator defaultMathEvaluator] unregisterFunctionWithName:@"e"];

And then implementing and registering my own euler() (basically copying the existing one). Is that crazy?
I am afraid since unregisterFunction is deprecated ...

**Comment by blackjack75** [comment]
Well I found a frictionless way to do it, subclassing DDMathParser and overloading the evaluateFunctionExpression method.

It's a bit dirty but it's better than maintaining a fork just for that.`

- (NSNumber *)_evaluateFunctionExpression:(_DDFunctionExpression *)e withSubstitutions:(NSDictionary *)substitutions error:(NSError **)error {
    
    NSLog(@"evaluating function express:%@",[e function]);
    
    if ([[e function] isEqualToString:@"e"])
    {
        *error = [NSError errorWithDomain:DDMathParserErrorDomain
                                     code:DDErrorCodeUnresolvedFunction
                                 userInfo:@{NSLocalizedDescriptionKey: [NSString stringWithFormat:@"unable to resolve function: %@", [e function]],
                                            DDUnknownFunctionKey: [e function]}];
        return nil;
    }
(...)
 `
Closing this issue. Thanks for your comments!

**Comment by davedelong** [comment]
I think an easier approach might be to delete the implementation of the `e` function: https://github.com/davedelong/DDMathParser/blob/master/DDMathParser/_DDFunctionEvaluator.m#L931

**Comment by blackjack75** [comment]
Sure. That was the obvious one. I wanted as much as possible to avoid maintaining a fork just for that. Thanks for your kind help!
